spring:
  datasource:
    druid:
      db-type: com.alibaba.druid.pool.vendor.MySqlExceptionSorter
      url: jdbc:mysql://10.0.8.18:3306/liaimsChannel
      username: liaimsChannel
      password: Gq42F2!3f
      driver-class-name: com.mysql.jdbc.Driver